default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>


development:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL', 'postgres://localhost/admin_development') %>

test:
  <<: *default
  url: <%= ENV.fetch('TEST_DATABASE_URL', 'postgres://localhost/admin_test') %>

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    <<: *primary_production
    database: admin_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: admin_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: admin_production_cable
    migrations_paths: db/cable_migrate
