version: "3.8"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: touhou_arrangement_chronicle_development
    ports:
      - '15432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db/schema:/tmp/db/schema

  migrate:
    build:
      context: .
      dockerfile: "./docker/psqldef/Dockerfile"
    volumes:
      - ./db:/app/db
      - go_pkg:/go/pkg
    working_dir: /app
    command:
      - "./psqldef"
      - "--file"
      - "./db/schema/schema.sql"
      - "--host"
      - "db"
      - "--port"
      - "15432"
      - "touhou_arrangement_chronicle_development"
    depends_on:
      - db
    profiles:
      - extra

  seeder:
    image: golang:1.21
    stdin_open: true
    tty: true
    depends_on:
      - db
    profiles:
      - extra
    environment:
      CONNECT_URL: "postgres://postgres:@db:5432/touhou_arrangement_chronicle_development?sslmode=disable"
      BUNDEBUG: 1
    volumes:
      - .:/app
      - go_pkg:/go/pkg
    working_dir: /app
    command:
      - "go"
      - "run"
      - "cmd/seeder/main.go"

  indexer:
    image: golang:1.21
    stdin_open: true
    tty: true
    depends_on:
      - db
      - meilisearch
    profiles:
      - extra
    environment:
      CONNECT_URL: "postgres://postgres:@db:5432/touhou_arrangement_chronicle_development?sslmode=disable"
      BUNDEBUG: 1
      MEILISEARCH_HOST: "http://meilisearch:7700"
      MEILISEARCH_API_KEY: "MASTER_KEY"
    volumes:
      - .:/app
      - go_pkg:/go/pkg
    working_dir: /app
    command:
      - "go"
      - "run"
      - "cmd/indexer/main.go"
      - "cmd/indexer/original_songs.go"
      - "cmd/indexer/albums.go"
      - "cmd/indexer/songs.go"
      - "cmd/indexer/setup.go"

  importer:
    image: golang:1.21
    stdin_open: true
    tty: true
    depends_on:
      - db
    profiles:
      - extra
    environment:
      CONNECT_URL: "postgres://postgres:@db:5432/touhou_arrangement_chronicle_development?sslmode=disable"
      BUNDEBUG: 1
    volumes:
      - .:/app
      - go_pkg:/go/pkg
    working_dir: /app
    command:
      - "go"
      - "run"
      - "cmd/importer/main.go"
      - "cmd/importer/import_events.go"
      - "cmd/importer/import_circles.go"
      - "cmd/importer/import_artists.go"
      - "cmd/importer/import_albums_and_songs.go"
      - "cmd/importer/import_album_service_urls.go"

  meilisearch:
    image: getmeili/meilisearch:prototype-japanese-4
    volumes:
      - meili-data:/meili_data
    ports:
      - '17700:7700'
    command:
      - "meilisearch"
      - "--master-key=MASTER_KEY"

  web: &web
    build:
      context: .
      dockerfile: "./docker/admin/Dockerfile"
    image: web:1.0.0
    stdin_open: true
    tty: true
    volumes:
      - ./admin/.:/app:cached
      - bundle:/app/vendor/bundle
      - rails_cache:/app/tmp/cache
    tmpfs:
      - /tmp
    environment:
      BUNDLE_PATH: "/app/vendor/bundle"
      BOOTSNAP_CACHE_DIR: "/app/vendor/bundle"
      DATABASE_URL: "postgres://postgres:postgres@db:5432"
      EDITOR: "vim"
      HISTFILE: "/app/log/.bash_history"
      RAILS_MASTER_KEY:
      WD_INSTALL_DIR: "/usr/local/bin"
    depends_on:
      - db
    command: ["bin/rails", "server", "-b", "0.0.0.0"]
    expose: ["3000"]
    ports: ["3000:3000"]
    user: root
    working_dir: /app

  server:
    build:
      context: .
      dockerfile: "./docker/server/Dockerfile"
    stdin_open: true
    tty: true
    depends_on:
      - db
    ports:
      - '8080:8080'
    environment:
      CONNECT_URL: "postgres://postgres:@db:5432/touhou_arrangement_chronicle_development?sslmode=disable"
    volumes:
      - .:/app
      - go_pkg:/go/pkg

volumes:
  go_pkg:
  postgres:
  meili-data:
    driver: local
  bundle:
  rails_cache:
