services:
  postgres17:
    image: postgres:17
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '15432:5432'
    volumes:
      - postgres-17:/var/lib/postgresql/data

  dbmate:
    image: ghcr.io/amacneil/dbmate:latest
    depends_on:
      - postgres17
    environment:
      DATABASE_URL: postgres://postgres@postgres17:5432/touhou_arrangement_chronicle_development?sslmode=disable
      TEST_DATABASE_URL: postgres://postgres@postgres17:5432/touhou_arrangement_chronicle_test?sslmode=disable
    volumes:
      - ./db:/db
    profiles:
      - dbmate

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "17700:7700"
    volumes:
      - meilisearch_data:/meili_data
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}
      - MEILI_NO_ANALYTICS=true
      - MEILI_ENV=development

volumes:
  postgres-17:
  meilisearch_data:
