services:
  postgres17:
    image: postgres:17
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '15432:5432'
    volumes:
      - postgres-17:/var/lib/postgresql/data

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile.dev
      args:
        - BUNDLE_PACKAGER__DEV=${BUNDLE_PACKAGER__DEV}
    stdin_open: true
    tty: true
    command: bash -c "bundle install --jobs=4 && rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    environment:
      BUNDLE_PATH: "/usr/local/bundle"
      BOOTSNAP_CACHE_DIR: "/usr/local/bundle"
      EDITOR: "vim"
      HISTFILE: "/app/log/.bash_history"
      RAILS_MASTER_KEY:
      WD_INSTALL_DIR: "/usr/local/bin"
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres@postgres17:5432/touhou_arrangement_chronicle_development
      TEST_DATABASE_URL: postgres://postgres@postgres17:5432/touhou_arrangement_chronicle_test
      MEILI_HOST: http://meilisearch:7700
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY:-masterKey}
    volumes:
      - ./admin:/app
      - admin_bundle:/usr/local/bundle
    ports:
      - "13000:3000"
    depends_on:
      - postgres17
      - meilisearch

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development-env
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    ports:
      - "15173:5173"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres@postgres17:5432/touhou_arrangement_chronicle_development
      - AUTH0_CALLBACK_URL=http://localhost:15173/auth/auth0/callback
      - POSTGRES_HOST=postgres17
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_DB=touhou_arrangement_chronicle_development
    depends_on:
      - postgres17
    restart: unless-stopped

  dbmate:
    image: ghcr.io/amacneil/dbmate:latest
    depends_on:
      - postgres17
    environment:
      DATABASE_URL: postgres://postgres@postgres17:5432/touhou_arrangement_chronicle_development?sslmode=disable
      TEST_DATABASE_URL: postgres://postgres@postgres17:5432/touhou_arrangement_chronicle_test?sslmode=disable
    volumes:
      - ./db:/db
    profiles:
      - dbmate

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "17700:7700"
    volumes:
      - meilisearch_data:/meili_data
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}
      - MEILI_NO_ANALYTICS=true
      - MEILI_ENV=development

volumes:
  postgres-17:
  meilisearch_data:
  admin_bundle:
