services:
  postgres16:
    image: postgres:16-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: touhou_arrangement_chronicle_development
    ports:
      - '15432:5432'
    volumes:
      - postgres-16:/var/lib/postgresql/data
      - ./db/schema:/tmp/db/schema

  migrate:
    build:
      context: .
      dockerfile: "./docker/psqldef/Dockerfile"
    volumes:
      - ./db:/app/db
      - go_pkg:/go/pkg
    working_dir: /app
    command:
      - "./psqldef"
      - "--file"
      - "./db/schema/schema.sql"
      - "--host"
      - "postgres16"
      - "--port"
      - "5432"
      - "touhou_arrangement_chronicle_development"
    depends_on:
      - postgres16
    profiles:
      - extra

  seeder:
    image: golang:1.22
    stdin_open: true
    tty: true
    depends_on:
      - postgres16
    profiles:
      - extra
    environment:
      CONNECT_URL: "postgres://postgres:@postgres16:5432/touhou_arrangement_chronicle_development?sslmode=disable"
      BUNDEBUG: 1
    volumes:
      - .:/app
      - go_pkg:/go/pkg
    working_dir: /app
    command:
      - "go"
      - "run"
      - "tools/cmd/seeder/main.go"

  indexer:
    image: golang:1.22
    stdin_open: true
    tty: true
    depends_on:
      - postgres16
      - meilisearch
    profiles:
      - extra
    environment:
      CONNECT_URL: "postgres://postgres:@postgres16:5432/touhou_arrangement_chronicle_development?sslmode=disable"
      BUNDEBUG: 1
      MEILISEARCH_HOST: "http://meilisearch:7700"
      MEILISEARCH_API_KEY: "MASTER_KEY"
    volumes:
      - .:/app
      - go_pkg:/go/pkg
    working_dir: /app
    command:
      - "go"
      - "run"
      - "tools/cmd/indexer/main.go"
      - "tools/cmd/indexer/original_songs.go"
      - "tools/cmd/indexer/albums.go"
      - "tools/cmd/indexer/songs.go"
      - "tools/cmd/indexer/setup.go"

  importer:
    image: golang:1.22
    stdin_open: true
    tty: true
    depends_on:
      - postgres16
    profiles:
      - extra
    environment:
      CONNECT_URL: "postgres://postgres:@postgres16:5432/touhou_arrangement_chronicle_development?sslmode=disable"
      BUNDEBUG: 1
    volumes:
      - .:/app
      - go_pkg:/go/pkg
    working_dir: /app
    command:
      - "go"
      - "run"
      - "tools/cmd/importer/main.go"
      - "tools/cmd/importer/import_events.go"
      - "tools/cmd/importer/import_circles.go"
      - "tools/cmd/importer/import_artists.go"
      - "tools/cmd/importer/import_albums_and_songs.go"
      - "tools/cmd/importer/import_album_service_urls.go"

  meilisearch:
    image: getmeili/meilisearch:prototype-japanese-10
    volumes:
      - meili-data:/meili_data
    ports:
      - '17700:7700'
    command:
      - "meilisearch"
      - "--master-key=MASTER_KEY"

  admin: &admin
    build:
      context: .
      dockerfile: "./docker/admin/Dockerfile"
    image: admin:1.0.0
    stdin_open: true
    tty: true
    volumes:
      - ./admin/.:/app:cached
      - bundle:/app/vendor/bundle
      - rails_cache:/app/tmp/cache
    tmpfs:
      - /tmp
    environment:
      BUNDLE_PATH: "/app/vendor/bundle"
      BOOTSNAP_CACHE_DIR: "/app/vendor/bundle"
      DATABASE_URL: "postgres://postgres:postgres@postgres16:5432"
      EDITOR: "vim"
      HISTFILE: "/app/log/.bash_history"
      RAILS_MASTER_KEY:
      WD_INSTALL_DIR: "/usr/local/bin"
    depends_on:
      - postgres16
      - admin-tailwind
    command: bash -c "bundle install --jobs=4 && rm -f tmp/pids/server.pid && ./bin/rails s -p 3000 -b '0.0.0.0'"
    expose:
      - '3000'
    ports:
      - '3000:3000'
    user: root
    working_dir: /app

  admin-tailwind:
    build:
      context: .
      dockerfile: "./docker/admin/Dockerfile"
    command: bin/rails tailwindcss:watch
    tty: true
    volumes:
      - ./admin/.:/app:cached
      - bundle:/app/vendor/bundle
      - rails_cache:/app/tmp/cache
    tmpfs:
      - /tmp
    environment:
      BUNDLE_PATH: "/app/vendor/bundle"
      BOOTSNAP_CACHE_DIR: "/app/vendor/bundle"

  frontend:
    build:
      context: .
      dockerfile: "./docker/frontend/Dockerfile"
    image: frontend:1.0.0
    stdin_open: true
    tty: true
    expose:
      - '5173'
    ports:
      - '5173:5173'
    working_dir: /app
    volumes:
      - ./frontend/.:/app:cached
      - node_modules:/app/node_modules
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - postgres16
    command: bash -c "npm install && npm run dev"

volumes:
  go_pkg:
  postgres-16:
  meili-data:
    driver: local
  bundle:
  rails_cache:
  node_modules:
