// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Event struct {
	ID          string       `json:"id"`
	EventSeries *EventSeries `json:"eventSeries"`
	Name        string       `json:"name"`
	DisplayName string       `json:"displayName"`
	Slug        string       `json:"slug"`
	StartDate   *string      `json:"startDate,omitempty"`
	EndDate     *string      `json:"endDate,omitempty"`
	EventStatus EventStatus  `json:"eventStatus"`
	Format      EventFormat  `json:"format"`
	RegionCode  string       `json:"regionCode"`
	Address     string       `json:"address"`
	Description string       `json:"description"`
	URL         string       `json:"url"`
	TwitterURL  string       `json:"twitterUrl"`
	SubEvents   []*SubEvent  `json:"subEvents"`
}

type EventSeries struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	DisplayName string   `json:"displayName"`
	Slug        string   `json:"slug"`
	Events      []*Event `json:"events"`
}

type OriginalSong struct {
	ID                      string                                `json:"id"`
	Product                 *Product                              `json:"product"`
	Name                    string                                `json:"name"`
	Composer                string                                `json:"composer"`
	Arranger                string                                `json:"arranger"`
	TrackNumber             int                                   `json:"trackNumber"`
	IsOriginal              bool                                  `json:"isOriginal"`
	SourceID                string                                `json:"sourceId"`
	DistributionServiceURLs []*OriginalSongDistributionServiceURL `json:"distributionServiceURLs"`
}

type OriginalSongDistributionServiceURL struct {
	ID           string              `json:"id"`
	OriginalSong *OriginalSong       `json:"originalSong"`
	Service      DistributionService `json:"service"`
	URL          string              `json:"url"`
}

type Product struct {
	ID                      string                           `json:"id"`
	Name                    string                           `json:"name"`
	ShortName               string                           `json:"shortName"`
	ProductType             ProductType                      `json:"productType"`
	SeriesNumber            float64                          `json:"seriesNumber"`
	OriginalSongs           []*OriginalSong                  `json:"originalSongs"`
	DistributionServiceURLs []*ProductDistributionServiceURL `json:"distributionServiceURLs"`
}

type ProductDistributionServiceURL struct {
	ID      string              `json:"id"`
	Product *Product            `json:"product"`
	Service DistributionService `json:"service"`
	URL     string              `json:"url"`
}

type SubEvent struct {
	ID          string      `json:"id"`
	Event       *Event      `json:"event"`
	Name        string      `json:"name"`
	DisplayName string      `json:"displayName"`
	Slug        string      `json:"slug"`
	Date        *string     `json:"date,omitempty"`
	EventStatus EventStatus `json:"eventStatus"`
	Description string      `json:"description"`
}

type DistributionService string

const (
	DistributionServiceSpotify      DistributionService = "SPOTIFY"
	DistributionServiceAppleMusic   DistributionService = "APPLE_MUSIC"
	DistributionServiceYoutubeMusic DistributionService = "YOUTUBE_MUSIC"
	DistributionServiceLineMusic    DistributionService = "LINE_MUSIC"
	DistributionServiceItunes       DistributionService = "ITUNES"
	DistributionServiceYoutube      DistributionService = "YOUTUBE"
	DistributionServiceNicovideo    DistributionService = "NICOVIDEO"
	DistributionServiceSoundCloud   DistributionService = "SOUND_CLOUD"
)

var AllDistributionService = []DistributionService{
	DistributionServiceSpotify,
	DistributionServiceAppleMusic,
	DistributionServiceYoutubeMusic,
	DistributionServiceLineMusic,
	DistributionServiceItunes,
	DistributionServiceYoutube,
	DistributionServiceNicovideo,
	DistributionServiceSoundCloud,
}

func (e DistributionService) IsValid() bool {
	switch e {
	case DistributionServiceSpotify, DistributionServiceAppleMusic, DistributionServiceYoutubeMusic, DistributionServiceLineMusic, DistributionServiceItunes, DistributionServiceYoutube, DistributionServiceNicovideo, DistributionServiceSoundCloud:
		return true
	}
	return false
}

func (e DistributionService) String() string {
	return string(e)
}

func (e *DistributionService) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DistributionService(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DistributionService", str)
	}
	return nil
}

func (e DistributionService) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type EventFormat string

const (
	EventFormatOffline EventFormat = "OFFLINE"
	EventFormatOnline  EventFormat = "ONLINE"
	EventFormatMixed   EventFormat = "MIXED"
)

var AllEventFormat = []EventFormat{
	EventFormatOffline,
	EventFormatOnline,
	EventFormatMixed,
}

func (e EventFormat) IsValid() bool {
	switch e {
	case EventFormatOffline, EventFormatOnline, EventFormatMixed:
		return true
	}
	return false
}

func (e EventFormat) String() string {
	return string(e)
}

func (e *EventFormat) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EventFormat(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EventFormat", str)
	}
	return nil
}

func (e EventFormat) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type EventStatus string

const (
	EventStatusScheduled   EventStatus = "SCHEDULED"
	EventStatusCancelled   EventStatus = "CANCELLED"
	EventStatusPostpone    EventStatus = "POSTPONE"
	EventStatusRescheduled EventStatus = "RESCHEDULED"
	EventStatusMovedOnline EventStatus = "MOVED_ONLINE"
	EventStatusOther       EventStatus = "OTHER"
)

var AllEventStatus = []EventStatus{
	EventStatusScheduled,
	EventStatusCancelled,
	EventStatusPostpone,
	EventStatusRescheduled,
	EventStatusMovedOnline,
	EventStatusOther,
}

func (e EventStatus) IsValid() bool {
	switch e {
	case EventStatusScheduled, EventStatusCancelled, EventStatusPostpone, EventStatusRescheduled, EventStatusMovedOnline, EventStatusOther:
		return true
	}
	return false
}

func (e EventStatus) String() string {
	return string(e)
}

func (e *EventStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EventStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EventStatus", str)
	}
	return nil
}

func (e EventStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ProductType string

const (
	ProductTypePc98                ProductType = "PC98"
	ProductTypeWindows             ProductType = "WINDOWS"
	ProductTypeZunsMusicCollection ProductType = "ZUNS_MUSIC_COLLECTION"
	ProductTypeAkyusUntouchedScore ProductType = "AKYUS_UNTOUCHED_SCORE"
	ProductTypeCommercialBooks     ProductType = "COMMERCIAL_BOOKS"
	ProductTypeTasofro             ProductType = "TASOFRO"
	ProductTypeOther               ProductType = "OTHER"
)

var AllProductType = []ProductType{
	ProductTypePc98,
	ProductTypeWindows,
	ProductTypeZunsMusicCollection,
	ProductTypeAkyusUntouchedScore,
	ProductTypeCommercialBooks,
	ProductTypeTasofro,
	ProductTypeOther,
}

func (e ProductType) IsValid() bool {
	switch e {
	case ProductTypePc98, ProductTypeWindows, ProductTypeZunsMusicCollection, ProductTypeAkyusUntouchedScore, ProductTypeCommercialBooks, ProductTypeTasofro, ProductTypeOther:
		return true
	}
	return false
}

func (e ProductType) String() string {
	return string(e)
}

func (e *ProductType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProductType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProductType", str)
	}
	return nil
}

func (e ProductType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
