// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Album struct {
	ID                string                         `json:"id"`
	Name              string                         `json:"name"`
	NameReading       string                         `json:"nameReading"`
	Slug              string                         `json:"slug"`
	ReleaseCircleName string                         `json:"releaseCircleName"`
	ReleaseDate       *string                        `json:"releaseDate,omitempty"`
	Event             *Event                         `json:"event,omitempty"`
	SubEvent          *SubEvent                      `json:"subEvent,omitempty"`
	SearchEnabled     bool                           `json:"searchEnabled"`
	AlbumNumber       string                         `json:"albumNumber"`
	EventPrice        *string                        `json:"eventPrice,omitempty"`
	Currency          string                         `json:"currency"`
	Credit            string                         `json:"credit"`
	Introduction      string                         `json:"introduction"`
	URL               string                         `json:"url"`
	Circles           []*Circle                      `json:"circles"`
	ConsignmentShops  []*ConsignmentShop             `json:"consignmentShops"`
	DistributionUrls  []*AlbumDistributionServiceURL `json:"distributionUrls"`
	Upcs              []*Upc                         `json:"upcs"`
	Genres            []*AlbumGenre                  `json:"genres"`
	Tags              []*AlbumTag                    `json:"tags"`
}

type AlbumDistributionServiceURL struct {
	ID      string              `json:"id"`
	Service DistributionService `json:"service"`
	URL     string              `json:"url"`
}

type AlbumGenre struct {
	ID     string `json:"id"`
	Album  *Album `json:"album"`
	Genre  *Genre `json:"genre"`
	Locked bool   `json:"locked"`
}

type AlbumTag struct {
	ID     string `json:"id"`
	Album  *Album `json:"album"`
	Tag    *Tag   `json:"tag"`
	Locked bool   `json:"locked"`
}

type Artist struct {
	ID                  string            `json:"id"`
	Name                string            `json:"name"`
	NameReading         string            `json:"nameReading"`
	Slug                string            `json:"slug"`
	InitialLetterType   InitialLetterType `json:"initialLetterType"`
	InitialLetterDetail string            `json:"initialLetterDetail"`
	Description         string            `json:"description"`
	URL                 string            `json:"url"`
	BlogURL             string            `json:"blogUrl"`
	TwitterURL          string            `json:"twitterUrl"`
	YoutubeChannelURL   string            `json:"youtubeChannelUrl"`
}

type Circle struct {
	ID                  string            `json:"id"`
	Name                string            `json:"name"`
	NameReading         string            `json:"nameReading"`
	Slug                string            `json:"slug"`
	InitialLetterType   InitialLetterType `json:"initialLetterType"`
	InitialLetterDetail string            `json:"initialLetterDetail"`
	Description         string            `json:"description"`
	URL                 string            `json:"url"`
	BlogURL             string            `json:"blogUrl"`
	TwitterURL          string            `json:"twitterUrl"`
	YoutubeChannelURL   string            `json:"youtubeChannelUrl"`
	Genres              []*CircleGenre    `json:"genres"`
	Tags                []*CircleTag      `json:"tags"`
}

type CircleGenre struct {
	ID     string  `json:"id"`
	Circle *Circle `json:"circle"`
	Genre  *Genre  `json:"genre"`
	Locked bool    `json:"locked"`
}

type CircleTag struct {
	ID     string  `json:"id"`
	Circle *Circle `json:"circle"`
	Tag    *Tag    `json:"tag"`
	Locked bool    `json:"locked"`
}

type ConsignmentShop struct {
	ID          string `json:"id"`
	Album       *Album `json:"album"`
	Shop        Shop   `json:"shop"`
	URL         string `json:"url"`
	TaxIncluded bool   `json:"taxIncluded"`
	ShopPrice   string `json:"shopPrice"`
	Currency    string `json:"currency"`
}

type Event struct {
	ID          string       `json:"id"`
	Series      *EventSeries `json:"series"`
	Name        string       `json:"name"`
	DisplayName string       `json:"displayName"`
	Slug        string       `json:"slug"`
	StartDate   *string      `json:"startDate,omitempty"`
	EndDate     *string      `json:"endDate,omitempty"`
	Status      EventStatus  `json:"status"`
	Format      EventFormat  `json:"format"`
	RegionCode  string       `json:"regionCode"`
	Address     string       `json:"address"`
	Description string       `json:"description"`
	URL         string       `json:"url"`
	TwitterURL  string       `json:"twitterUrl"`
	SubEvents   []*SubEvent  `json:"subEvents"`
}

type EventSeries struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	DisplayName string   `json:"displayName"`
	Slug        string   `json:"slug"`
	Events      []*Event `json:"events"`
}

type Genre struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Isrc struct {
	ID   string `json:"id"`
	Song *Song  `json:"song"`
	Isrc string `json:"isrc"`
}

type OriginalSong struct {
	ID               string                                `json:"id"`
	Product          *Product                              `json:"product"`
	Name             string                                `json:"name"`
	Composer         string                                `json:"composer"`
	Arranger         string                                `json:"arranger"`
	TrackNumber      int                                   `json:"trackNumber"`
	IsOriginal       bool                                  `json:"isOriginal"`
	SourceID         string                                `json:"sourceId"`
	DistributionUrls []*OriginalSongDistributionServiceURL `json:"distributionUrls"`
}

type OriginalSongDistributionServiceURL struct {
	ID      string              `json:"id"`
	Service DistributionService `json:"service"`
	URL     string              `json:"url"`
}

type Product struct {
	ID               string                           `json:"id"`
	Name             string                           `json:"name"`
	ShortName        string                           `json:"shortName"`
	ProductType      ProductType                      `json:"productType"`
	SeriesNumber     float64                          `json:"seriesNumber"`
	OriginalSongs    []*OriginalSong                  `json:"originalSongs"`
	DistributionUrls []*ProductDistributionServiceURL `json:"distributionUrls"`
}

type ProductDistributionServiceURL struct {
	ID      string              `json:"id"`
	Service DistributionService `json:"service"`
	URL     string              `json:"url"`
}

type Song struct {
	ID                  string                        `json:"id"`
	Circle              *Circle                       `json:"circle,omitempty"`
	Album               *Album                        `json:"album"`
	Name                string                        `json:"name"`
	NameReading         string                        `json:"nameReading"`
	Slug                string                        `json:"slug"`
	DiscNumber          int                           `json:"discNumber"`
	TrackNumber         int                           `json:"trackNumber"`
	ReleaseDate         *string                       `json:"releaseDate,omitempty"`
	SearchEnabled       bool                          `json:"searchEnabled"`
	Length              *int                          `json:"length,omitempty"`
	Bpm                 *int                          `json:"bpm,omitempty"`
	Description         string                        `json:"description"`
	DisplayComposer     string                        `json:"displayComposer"`
	DisplayArranger     string                        `json:"displayArranger"`
	DisplayRearranger   string                        `json:"displayRearranger"`
	DisplayLyricist     string                        `json:"displayLyricist"`
	DisplayVocalist     string                        `json:"displayVocalist"`
	DisplayOriginalSong string                        `json:"displayOriginalSong"`
	DistributionUrls    []*SongDistributionServiceURL `json:"distributionUrls"`
	Isrcs               []*Isrc                       `json:"isrcs"`
	ArrangeCircles      []*Circle                     `json:"arrangeCircles"`
	Composers           []*Artist                     `json:"composers"`
	Arrangers           []*Artist                     `json:"arrangers"`
	Rearrangers         []*Artist                     `json:"rearrangers"`
	Lyricists           []*Artist                     `json:"lyricists"`
	Vocalists           []*Artist                     `json:"vocalists"`
	OriginalSongs       []*OriginalSong               `json:"originalSongs"`
	Circles             []*Circle                     `json:"circles"`
	Genres              []*SongGenre                  `json:"genres"`
	Tags                []*SongTag                    `json:"tags"`
}

type SongDistributionServiceURL struct {
	ID      string              `json:"id"`
	Service DistributionService `json:"service"`
	URL     string              `json:"url"`
}

type SongGenre struct {
	ID     string `json:"id"`
	Song   *Song  `json:"song"`
	Genre  *Genre `json:"genre"`
	Locked bool   `json:"locked"`
}

type SongTag struct {
	ID     string `json:"id"`
	Song   *Song  `json:"song"`
	Tag    *Tag   `json:"tag"`
	Locked bool   `json:"locked"`
}

type SubEvent struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	DisplayName string      `json:"displayName"`
	Slug        string      `json:"slug"`
	Date        *string     `json:"date,omitempty"`
	Status      EventStatus `json:"status"`
	Description string      `json:"description"`
}

type Tag struct {
	ID      string  `json:"id"`
	Name    string  `json:"name"`
	TagType TagType `json:"tagType"`
}

type Upc struct {
	ID    string `json:"id"`
	Album *Album `json:"album"`
	Upc   string `json:"upc"`
}

type DistributionService string

const (
	DistributionServiceSpotify      DistributionService = "SPOTIFY"
	DistributionServiceAppleMusic   DistributionService = "APPLE_MUSIC"
	DistributionServiceYoutubeMusic DistributionService = "YOUTUBE_MUSIC"
	DistributionServiceLineMusic    DistributionService = "LINE_MUSIC"
	DistributionServiceItunes       DistributionService = "ITUNES"
	DistributionServiceYoutube      DistributionService = "YOUTUBE"
	DistributionServiceNicovideo    DistributionService = "NICOVIDEO"
	DistributionServiceSoundCloud   DistributionService = "SOUND_CLOUD"
)

var AllDistributionService = []DistributionService{
	DistributionServiceSpotify,
	DistributionServiceAppleMusic,
	DistributionServiceYoutubeMusic,
	DistributionServiceLineMusic,
	DistributionServiceItunes,
	DistributionServiceYoutube,
	DistributionServiceNicovideo,
	DistributionServiceSoundCloud,
}

func (e DistributionService) IsValid() bool {
	switch e {
	case DistributionServiceSpotify, DistributionServiceAppleMusic, DistributionServiceYoutubeMusic, DistributionServiceLineMusic, DistributionServiceItunes, DistributionServiceYoutube, DistributionServiceNicovideo, DistributionServiceSoundCloud:
		return true
	}
	return false
}

func (e DistributionService) String() string {
	return string(e)
}

func (e *DistributionService) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DistributionService(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DistributionService", str)
	}
	return nil
}

func (e DistributionService) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type EventFormat string

const (
	EventFormatOffline EventFormat = "OFFLINE"
	EventFormatOnline  EventFormat = "ONLINE"
	EventFormatMixed   EventFormat = "MIXED"
)

var AllEventFormat = []EventFormat{
	EventFormatOffline,
	EventFormatOnline,
	EventFormatMixed,
}

func (e EventFormat) IsValid() bool {
	switch e {
	case EventFormatOffline, EventFormatOnline, EventFormatMixed:
		return true
	}
	return false
}

func (e EventFormat) String() string {
	return string(e)
}

func (e *EventFormat) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EventFormat(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EventFormat", str)
	}
	return nil
}

func (e EventFormat) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type EventStatus string

const (
	EventStatusScheduled   EventStatus = "SCHEDULED"
	EventStatusCancelled   EventStatus = "CANCELLED"
	EventStatusPostpone    EventStatus = "POSTPONE"
	EventStatusRescheduled EventStatus = "RESCHEDULED"
	EventStatusMovedOnline EventStatus = "MOVED_ONLINE"
	EventStatusOther       EventStatus = "OTHER"
)

var AllEventStatus = []EventStatus{
	EventStatusScheduled,
	EventStatusCancelled,
	EventStatusPostpone,
	EventStatusRescheduled,
	EventStatusMovedOnline,
	EventStatusOther,
}

func (e EventStatus) IsValid() bool {
	switch e {
	case EventStatusScheduled, EventStatusCancelled, EventStatusPostpone, EventStatusRescheduled, EventStatusMovedOnline, EventStatusOther:
		return true
	}
	return false
}

func (e EventStatus) String() string {
	return string(e)
}

func (e *EventStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EventStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EventStatus", str)
	}
	return nil
}

func (e EventStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type InitialLetterType string

const (
	InitialLetterTypeSymbol   InitialLetterType = "SYMBOL"
	InitialLetterTypeNumber   InitialLetterType = "NUMBER"
	InitialLetterTypeAlphabet InitialLetterType = "ALPHABET"
	InitialLetterTypeHiragana InitialLetterType = "HIRAGANA"
	InitialLetterTypeKatakana InitialLetterType = "KATAKANA"
	InitialLetterTypeKanji    InitialLetterType = "KANJI"
	InitialLetterTypeOther    InitialLetterType = "OTHER"
)

var AllInitialLetterType = []InitialLetterType{
	InitialLetterTypeSymbol,
	InitialLetterTypeNumber,
	InitialLetterTypeAlphabet,
	InitialLetterTypeHiragana,
	InitialLetterTypeKatakana,
	InitialLetterTypeKanji,
	InitialLetterTypeOther,
}

func (e InitialLetterType) IsValid() bool {
	switch e {
	case InitialLetterTypeSymbol, InitialLetterTypeNumber, InitialLetterTypeAlphabet, InitialLetterTypeHiragana, InitialLetterTypeKatakana, InitialLetterTypeKanji, InitialLetterTypeOther:
		return true
	}
	return false
}

func (e InitialLetterType) String() string {
	return string(e)
}

func (e *InitialLetterType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InitialLetterType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InitialLetterType", str)
	}
	return nil
}

func (e InitialLetterType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ProductType string

const (
	ProductTypePc98                ProductType = "PC98"
	ProductTypeWindows             ProductType = "WINDOWS"
	ProductTypeZunsMusicCollection ProductType = "ZUNS_MUSIC_COLLECTION"
	ProductTypeAkyusUntouchedScore ProductType = "AKYUS_UNTOUCHED_SCORE"
	ProductTypeCommercialBooks     ProductType = "COMMERCIAL_BOOKS"
	ProductTypeTasofro             ProductType = "TASOFRO"
	ProductTypeOther               ProductType = "OTHER"
)

var AllProductType = []ProductType{
	ProductTypePc98,
	ProductTypeWindows,
	ProductTypeZunsMusicCollection,
	ProductTypeAkyusUntouchedScore,
	ProductTypeCommercialBooks,
	ProductTypeTasofro,
	ProductTypeOther,
}

func (e ProductType) IsValid() bool {
	switch e {
	case ProductTypePc98, ProductTypeWindows, ProductTypeZunsMusicCollection, ProductTypeAkyusUntouchedScore, ProductTypeCommercialBooks, ProductTypeTasofro, ProductTypeOther:
		return true
	}
	return false
}

func (e ProductType) String() string {
	return string(e)
}

func (e *ProductType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProductType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProductType", str)
	}
	return nil
}

func (e ProductType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Shop string

const (
	ShopAkibaHobby    Shop = "AKIBA_HOBBY"
	ShopAkibaoo       Shop = "AKIBAOO"
	ShopAnimate       Shop = "ANIMATE"
	ShopBookmate      Shop = "BOOKMATE"
	ShopBooth         Shop = "BOOTH"
	ShopDiverseDirect Shop = "DIVERSE_DIRECT"
	ShopGrep          Shop = "GREP"
	ShopMelonbooks    Shop = "MELONBOOKS"
	ShopTanocstore    Shop = "TANOCSTORE"
	ShopToranoana     Shop = "TORANOANA"
)

var AllShop = []Shop{
	ShopAkibaHobby,
	ShopAkibaoo,
	ShopAnimate,
	ShopBookmate,
	ShopBooth,
	ShopDiverseDirect,
	ShopGrep,
	ShopMelonbooks,
	ShopTanocstore,
	ShopToranoana,
}

func (e Shop) IsValid() bool {
	switch e {
	case ShopAkibaHobby, ShopAkibaoo, ShopAnimate, ShopBookmate, ShopBooth, ShopDiverseDirect, ShopGrep, ShopMelonbooks, ShopTanocstore, ShopToranoana:
		return true
	}
	return false
}

func (e Shop) String() string {
	return string(e)
}

func (e *Shop) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Shop(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Shop", str)
	}
	return nil
}

func (e Shop) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type TagType string

const (
	TagTypeUnknown    TagType = "UNKNOWN"
	TagTypeGenre      TagType = "GENRE"
	TagTypeAmbience   TagType = "AMBIENCE"
	TagTypeInstrument TagType = "INSTRUMENT"
)

var AllTagType = []TagType{
	TagTypeUnknown,
	TagTypeGenre,
	TagTypeAmbience,
	TagTypeInstrument,
}

func (e TagType) IsValid() bool {
	switch e {
	case TagTypeUnknown, TagTypeGenre, TagTypeAmbience, TagTypeInstrument:
		return true
	}
	return false
}

func (e TagType) String() string {
	return string(e)
}

func (e *TagType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TagType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TagType", str)
	}
	return nil
}

func (e TagType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
