package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"fmt"

	"github.com/shiroemons/touhou_arrangement_chronicle/graph/generated"
	"github.com/shiroemons/touhou_arrangement_chronicle/graph/model"
	"github.com/shiroemons/touhou_arrangement_chronicle/internal/loader"
)

// Product is the resolver for the product field.
func (r *originalSongResolver) Product(ctx context.Context, obj *model.OriginalSong) (*model.Product, error) {
	product, err := loader.LoadProduct(ctx, obj.Product.ID)
	if err != nil {
		return nil, err
	}
	return product, nil
}

// GetProductByID is the resolver for the getProductById field.
func (r *queryResolver) GetProductByID(ctx context.Context, id string) (*model.Product, error) {
	product, err := r.productSrv.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	return product.ToGraphQL(), nil
}

// GetOriginalSongByID is the resolver for the getOriginalSongById field.
func (r *queryResolver) GetOriginalSongByID(ctx context.Context, id string) (*model.OriginalSong, error) {
	os, err := r.originalSongSrv.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	return os.ToGraphQL(), nil
}

// GetProducts is the resolver for the getProducts field.
func (r *queryResolver) GetProducts(ctx context.Context) ([]*model.Product, error) {
	products, err := r.productSrv.GetAll(ctx)
	if err != nil {
		return nil, err
	}
	return products.ToGraphQLs(), nil
}

// GetOriginalSongs is the resolver for the getOriginalSongs field.
func (r *queryResolver) GetOriginalSongs(ctx context.Context) ([]*model.OriginalSong, error) {
	os, err := r.originalSongSrv.GetAll(ctx)
	if err != nil {
		return nil, err
	}
	return os.ToGraphQLs(), nil
}

// GetEventSeriesByID is the resolver for the getEventSeriesById field.
func (r *queryResolver) GetEventSeriesByID(ctx context.Context, id string) (*model.EventSeries, error) {
	panic(fmt.Errorf("not implemented: GetEventSeriesByID - getEventSeriesById"))
}

// GetEventByID is the resolver for the getEventById field.
func (r *queryResolver) GetEventByID(ctx context.Context, id string) (*model.Event, error) {
	panic(fmt.Errorf("not implemented: GetEventByID - getEventById"))
}

// GetSubEventByID is the resolver for the getSubEventById field.
func (r *queryResolver) GetSubEventByID(ctx context.Context, id string) (*model.SubEvent, error) {
	panic(fmt.Errorf("not implemented: GetSubEventByID - getSubEventById"))
}

// GetEventSeries is the resolver for the getEventSeries field.
func (r *queryResolver) GetEventSeries(ctx context.Context) ([]*model.EventSeries, error) {
	panic(fmt.Errorf("not implemented: GetEventSeries - getEventSeries"))
}

// GetArtistByID is the resolver for the getArtistById field.
func (r *queryResolver) GetArtistByID(ctx context.Context, id string) (*model.Artist, error) {
	panic(fmt.Errorf("not implemented: GetArtistByID - getArtistById"))
}

// GetCircleByID is the resolver for the getCircleById field.
func (r *queryResolver) GetCircleByID(ctx context.Context, id string) (*model.Circle, error) {
	panic(fmt.Errorf("not implemented: GetCircleByID - getCircleById"))
}

// ArtistsByInitialLetterType is the resolver for the artistsByInitialLetterType field.
func (r *queryResolver) ArtistsByInitialLetterType(ctx context.Context, typeArg model.InitialLetterType) ([]*model.Artist, error) {
	panic(fmt.Errorf("not implemented: ArtistsByInitialLetterType - artistsByInitialLetterType"))
}

// CirclesByInitialLetterType is the resolver for the circlesByInitialLetterType field.
func (r *queryResolver) CirclesByInitialLetterType(ctx context.Context, typeArg model.InitialLetterType) ([]*model.Circle, error) {
	panic(fmt.Errorf("not implemented: CirclesByInitialLetterType - circlesByInitialLetterType"))
}

// GetAlbumByID is the resolver for the getAlbumById field.
func (r *queryResolver) GetAlbumByID(ctx context.Context, id string) (*model.Album, error) {
	panic(fmt.Errorf("not implemented: GetAlbumByID - getAlbumById"))
}

// GetSongByID is the resolver for the getSongById field.
func (r *queryResolver) GetSongByID(ctx context.Context, id string) (*model.Song, error) {
	panic(fmt.Errorf("not implemented: GetSongByID - getSongById"))
}

// GetGenres is the resolver for the getGenres field.
func (r *queryResolver) GetGenres(ctx context.Context) ([]*model.Genre, error) {
	panic(fmt.Errorf("not implemented: GetGenres - getGenres"))
}

// GetTags is the resolver for the getTags field.
func (r *queryResolver) GetTags(ctx context.Context) ([]*model.Tag, error) {
	panic(fmt.Errorf("not implemented: GetTags - getTags"))
}

// OriginalSong returns generated.OriginalSongResolver implementation.
func (r *Resolver) OriginalSong() generated.OriginalSongResolver { return &originalSongResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type originalSongResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
