package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"

	"github.com/shiroemons/touhou_arrangement_chronicle/graph/generated"
	"github.com/shiroemons/touhou_arrangement_chronicle/graph/model"
	"github.com/shiroemons/touhou_arrangement_chronicle/internal/loader"
)

// Event is the resolver for the event field.
func (r *albumResolver) Event(ctx context.Context, obj *model.Album) (*model.Event, error) {
	if obj.Event == nil {
		return nil, nil
	}
	event, err := loader.LoadEvent(ctx, obj.Event.ID)
	if err != nil {
		return nil, err
	}
	return event, nil
}

// SubEvent is the resolver for the subEvent field.
func (r *albumResolver) SubEvent(ctx context.Context, obj *model.Album) (*model.SubEvent, error) {
	if obj.SubEvent == nil {
		return nil, nil
	}
	subEvent, err := loader.LoadSubEvent(ctx, obj.SubEvent.ID)
	if err != nil {
		return nil, err
	}
	return subEvent, nil
}

// Series is the resolver for the series field.
func (r *eventResolver) Series(ctx context.Context, obj *model.Event) (*model.EventSeries, error) {
	if obj.Series == nil {
		return nil, nil
	}
	series, err := loader.LoadEventSeries(ctx, obj.Series.ID)
	if err != nil {
		return nil, err
	}
	return series, nil
}

// Product is the resolver for the product field.
func (r *originalSongResolver) Product(ctx context.Context, obj *model.OriginalSong) (*model.Product, error) {
	if obj.Product == nil {
		return nil, nil
	}
	product, err := loader.LoadProduct(ctx, obj.Product.ID)
	if err != nil {
		return nil, err
	}
	return product, nil
}

// ProductsByIds is the resolver for the productsByIds field.
func (r *queryResolver) ProductsByIds(ctx context.Context, ids []*model.IDClause) (*model.ProductsResponse, error) {
	_ids := make([]string, len(ids))
	for i, id := range ids {
		_ids[i] = id.ID
	}
	products, err := r.productSrv.GetProductsByIDs(ctx, _ids)
	if err != nil {
		return nil, err
	}
	//return product.ToGraphQL(), nil

	return &model.ProductsResponse{
		Products: products.ToGraphQLs(),
	}, nil
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context) (*model.ProductsResponse, error) {
	products, err := r.productSrv.GetAll(ctx)
	if err != nil {
		return nil, err
	}
	return &model.ProductsResponse{
		Products: products.ToGraphQLs(),
	}, nil
}

// OriginalSongsByIds is the resolver for the originalSongsByIds field.
func (r *queryResolver) OriginalSongsByIds(ctx context.Context, ids []*model.IDClause) (*model.OriginalSongsResponse, error) {
	_ids := make([]string, len(ids))
	for i, id := range ids {
		_ids[i] = id.ID
	}
	os, err := r.originalSongSrv.GetOriginalSongsByIDs(ctx, _ids)
	if err != nil {
		return nil, err
	}

	return &model.OriginalSongsResponse{
		OriginalSongs: os.ToGraphQLs(),
	}, nil
}

// OriginalSongs is the resolver for the originalSongs field.
func (r *queryResolver) OriginalSongs(ctx context.Context) (*model.OriginalSongsResponse, error) {
	os, err := r.originalSongSrv.GetAll(ctx)
	if err != nil {
		return nil, err
	}
	return &model.OriginalSongsResponse{
		OriginalSongs: os.ToGraphQLs(),
	}, nil
}

// EventSeriesByIds is the resolver for the eventSeriesByIds field.
func (r *queryResolver) EventSeriesByIds(ctx context.Context, ids []*model.IDClause) (*model.EventSeriesResponse, error) {
	_ids := make([]string, len(ids))
	for i, id := range ids {
		_ids[i] = id.ID
	}
	es, err := r.eventSeriesSrv.GetEventSeriesByIDs(ctx, _ids)
	if err != nil {
		return nil, err
	}

	return &model.EventSeriesResponse{
		EventSeries: es.ToGraphQLs(),
	}, nil
}

// EventSeries is the resolver for the eventSeries field.
func (r *queryResolver) EventSeries(ctx context.Context) (*model.EventSeriesResponse, error) {
	es, err := r.eventSeriesSrv.GetAll(ctx)
	if err != nil {
		return nil, err
	}

	return &model.EventSeriesResponse{
		EventSeries: es.ToGraphQLs(),
	}, nil
}

// EventsByIds is the resolver for the eventsByIds field.
func (r *queryResolver) EventsByIds(ctx context.Context, ids []*model.IDClause) (*model.EventsResponse, error) {
	_ids := make([]string, len(ids))
	for i, id := range ids {
		_ids[i] = id.ID
	}
	e, err := r.eventSrv.GetEventsByIDs(ctx, _ids)
	if err != nil {
		return nil, err
	}

	return &model.EventsResponse{
		Events: e.ToGraphQLs(),
	}, nil
}

// SubEventsByIds is the resolver for the subEventsByIds field.
func (r *queryResolver) SubEventsByIds(ctx context.Context, ids []*model.IDClause) (*model.SubEventsResponse, error) {
	_ids := make([]string, len(ids))
	for i, id := range ids {
		_ids[i] = id.ID
	}
	se, err := r.subEventSrv.GetSubEventsByIDs(ctx, _ids)
	if err != nil {
		return nil, err
	}

	return &model.SubEventsResponse{
		SubEvents: se.ToGraphQLs(),
	}, nil
}

// ArtistsByIds is the resolver for the artistsByIds field.
func (r *queryResolver) ArtistsByIds(ctx context.Context, ids []*model.IDClause) (*model.ArtistsResponse, error) {
	_ids := make([]string, len(ids))
	for i, id := range ids {
		_ids[i] = id.ID
	}
	artists, err := r.artistSrv.GetArtistsByIDs(ctx, _ids)
	if err != nil {
		return nil, err
	}

	return &model.ArtistsResponse{
		Artists: artists.ToGraphQLs(),
	}, nil
}

// ArtistsByInitialLetterType is the resolver for the artistsByInitialLetterType field.
func (r *queryResolver) ArtistsByInitialLetterType(ctx context.Context, typeArg model.InitialLetterType) (*model.ArtistsResponse, error) {
	artists, err := r.artistSrv.GetAllByInitialLetterType(ctx, typeArg)
	if err != nil {
		return nil, err
	}

	return &model.ArtistsResponse{
		Artists: artists.ToGraphQLs(),
	}, nil
}

// CirclesByIds is the resolver for the circlesByIds field.
func (r *queryResolver) CirclesByIds(ctx context.Context, ids []*model.IDClause) (*model.CirclesResponse, error) {
	_ids := make([]string, len(ids))
	for i, id := range ids {
		_ids[i] = id.ID
	}
	circles, err := r.circleSrv.GetCirclesByIDs(ctx, _ids)
	if err != nil {
		return nil, err
	}

	return &model.CirclesResponse{
		Circles: circles.ToGraphQLs(),
	}, nil
}

// CirclesByInitialLetterType is the resolver for the circlesByInitialLetterType field.
func (r *queryResolver) CirclesByInitialLetterType(ctx context.Context, typeArg model.InitialLetterType) (*model.CirclesResponse, error) {
	circles, err := r.circleSrv.GetAllByInitialLetterType(ctx, typeArg)
	if err != nil {
		return nil, err
	}

	return &model.CirclesResponse{
		Circles: circles.ToGraphQLs(),
	}, nil
}

// AlbumsByIds is the resolver for the albumsByIds field.
func (r *queryResolver) AlbumsByIds(ctx context.Context, ids []*model.IDClause) (*model.AlbumsResponse, error) {
	_ids := make([]string, len(ids))
	for i, id := range ids {
		_ids[i] = id.ID
	}
	albums, err := r.albumSrv.GetAlbumsByIDs(ctx, _ids)
	if err != nil {
		return nil, err
	}

	return &model.AlbumsResponse{
		Albums: albums.ToGraphQLs(),
	}, nil
}

// SongsByIds is the resolver for the songsByIds field.
func (r *queryResolver) SongsByIds(ctx context.Context, ids []*model.IDClause) (*model.SongsResponse, error) {
	_ids := make([]string, len(ids))
	for i, id := range ids {
		_ids[i] = id.ID
	}
	songs, err := r.songSrv.GetSongsByIDs(ctx, _ids)
	if err != nil {
		return nil, err
	}

	return &model.SongsResponse{
		Songs: songs.ToGraphQLs(),
	}, nil
}

// Genres is the resolver for the genres field.
func (r *queryResolver) Genres(ctx context.Context) (*model.GenresResponse, error) {
	genres, err := r.genreSrv.All(ctx)
	if err != nil {
		return nil, err
	}

	return &model.GenresResponse{
		Genres: genres.ToGraphQLs(),
	}, nil
}

// Tags is the resolver for the tags field.
func (r *queryResolver) Tags(ctx context.Context) (*model.TagsResponse, error) {
	tags, err := r.tagSrv.All(ctx)
	if err != nil {
		return nil, err
	}

	return &model.TagsResponse{
		Tags: tags.ToGraphQLs(),
	}, nil
}

// Circle is the resolver for the circle field.
func (r *songResolver) Circle(ctx context.Context, obj *model.Song) (*model.Circle, error) {
	if obj.Circle == nil {
		return nil, nil
	}
	circle, err := loader.LoadCircle(ctx, obj.Circle.ID)
	if err != nil {
		return nil, err
	}
	return circle, nil
}

// Album is the resolver for the album field.
func (r *songResolver) Album(ctx context.Context, obj *model.Song) (*model.Album, error) {
	if obj.Album == nil {
		return nil, nil
	}
	album, err := loader.LoadAlbum(ctx, obj.Album.ID)
	if err != nil {
		return nil, err
	}
	return album, nil
}

// Album returns generated.AlbumResolver implementation.
func (r *Resolver) Album() generated.AlbumResolver { return &albumResolver{r} }

// Event returns generated.EventResolver implementation.
func (r *Resolver) Event() generated.EventResolver { return &eventResolver{r} }

// OriginalSong returns generated.OriginalSongResolver implementation.
func (r *Resolver) OriginalSong() generated.OriginalSongResolver { return &originalSongResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Song returns generated.SongResolver implementation.
func (r *Resolver) Song() generated.SongResolver { return &songResolver{r} }

type albumResolver struct{ *Resolver }
type eventResolver struct{ *Resolver }
type originalSongResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type songResolver struct{ *Resolver }
