package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"fmt"

	"github.com/shiroemons/touhou_arrangement_chronicle/graph/generated"
	"github.com/shiroemons/touhou_arrangement_chronicle/graph/model"
)

// GetProductByID is the resolver for the getProductById field.
func (r *queryResolver) GetProductByID(ctx context.Context, id string) (*model.Product, error) {
	panic(fmt.Errorf("not implemented: GetProductByID - getProductById"))
}

// GetOriginalSongByID is the resolver for the getOriginalSongById field.
func (r *queryResolver) GetOriginalSongByID(ctx context.Context, id string) (*model.OriginalSong, error) {
	panic(fmt.Errorf("not implemented: GetOriginalSongByID - getOriginalSongById"))
}

// GetProducts is the resolver for the getProducts field.
func (r *queryResolver) GetProducts(ctx context.Context) ([]*model.Product, error) {
	panic(fmt.Errorf("not implemented: GetProducts - getProducts"))
}

// GetOriginalSongs is the resolver for the getOriginalSongs field.
func (r *queryResolver) GetOriginalSongs(ctx context.Context) ([]*model.OriginalSong, error) {
	panic(fmt.Errorf("not implemented: GetOriginalSongs - getOriginalSongs"))
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
