name: rubocop

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - admin/**

env:
  CI: "true"

jobs:
  rubocop:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: admin

    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Cache vendor/bundle
        uses: actions/cache@v4
        id: cache_gem
        with:
          path: vendor/bundle
          key: v1-gem-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            v1-gem-{{ runner.os }}-

      - name: Build and setup
        run: |
          gem install bundler --no-document -v $(grep "BUNDLED WITH" -1 Gemfile.lock | tail -n 1)
          bundle install --jobs 4 --retry 3

      - name: Run Rubocop
        run: |
          bundle exec rubocop --parallel
